### ISSUE TITLE
Error while installation on Raspberry Pi 3 with Hassio 

### ISSUE THREAD

**Issue by weinbrand** [coolchip/node-red-contrib-smartmeter#16]
Hi!

I keep getting the errors below while installation on a raspberry pi running HASSIO and the latest NodeRed Version (7.0.0). --> I have no clue what to do. Any advice?

Thanks a lot!

Christian

`2020-07-17T19:44:41.981Z installieren : node-red-contrib-smartmeter 0.3.1

2020-07-17T19:44:43.629Z npm install --no-audit --no-update-notifier --no-fund --save --save-prefix="~" --production node-red-contrib-smartmeter@0.3.1
2020-07-17T19:45:11.793Z [err] npm
2020-07-17T19:45:11.794Z [err]  WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
2020-07-17T19:45:31.492Z [out] 
2020-07-17T19:45:31.492Z [out] > @serialport/bindings@8.0.8 install /config/node-red/node_modules/@serialport/bindings
2020-07-17T19:45:31.492Z [out] > prebuild-install --tag-prefix @serialport/bindings@ || node-gyp rebuild
2020-07-17T19:45:31.492Z [out] 
2020-07-17T19:45:33.263Z [err] prebuild-install
2020-07-17T19:45:33.264Z [err]  
2020-07-17T19:45:33.264Z [err] WARN install No prebuilt binaries found (target=12.17.0 runtime=node arch=arm libc=musl platform=linux)
2020-07-17T19:45:39.035Z [err] gyp
2020-07-17T19:45:39.036Z [err]  
2020-07-17T19:45:39.036Z [err] ERR! build error
2020-07-17T19:45:39.036Z [err]  
2020-07-17T19:45:39.039Z [err] gyp
2020-07-17T19:45:39.040Z [err]  ERR!
2020-07-17T19:45:39.040Z [err]  stack
2020-07-17T19:45:39.040Z [err]  Error: not found: make
2020-07-17T19:45:39.040Z [err] gyp ERR!
2020-07-17T19:45:39.040Z [err]  stack
2020-07-17T19:45:39.040Z [err]      at getNotFoundError (/usr/lib/node_modules/npm/node_modules/which/which.js:13:12)
2020-07-17T19:45:39.040Z [err] gyp
2020-07-17T19:45:39.040Z [err]  
2020-07-17T19:45:39.041Z [err] ERR! 
2020-07-17T19:45:39.041Z [err] stack     at F (/usr/lib/node_modules/npm/node_modules/which/which.js:68:19)
2020-07-17T19:45:39.041Z [err] gyp
2020-07-17T19:45:39.041Z [err]  ERR!
2020-07-17T19:45:39.041Z [err]  stack
2020-07-17T19:45:39.041Z [err]      at E (/usr/lib/node_modules/npm/node_modules/which/which.js:80:29)
2020-07-17T19:45:39.041Z [err] gyp
2020-07-17T19:45:39.041Z [err]  ERR! 
2020-07-17T19:45:39.041Z [err] stack     at /usr/lib/node_modules/npm/node_modules/which/which.js:89:16
2020-07-17T19:45:39.042Z [err] gyp 
2020-07-17T19:45:39.042Z [err] ERR! 
2020-07-17T19:45:39.042Z [err] stack     at /usr/lib/node_modules/npm/node_modules/isexe/index.js:42:5
2020-07-17T19:45:39.042Z [err] gyp 
2020-07-17T19:45:39.042Z [err] ERR! 
2020-07-17T19:45:39.042Z [err] stack     at /usr/lib/node_modules/npm/node_modules/isexe/mode.js:8:5
2020-07-17T19:45:39.042Z [err] gyp
2020-07-17T19:45:39.042Z [err]  ERR!
2020-07-17T19:45:39.042Z [err]  stack     at FSReqCallback.oncomplete (fs.js:167:21)
2020-07-17T19:45:39.044Z [err] gyp
2020-07-17T19:45:39.044Z [err]  ERR! System Linux 4.19.106-v7
2020-07-17T19:45:39.044Z [err] gyp 
2020-07-17T19:45:39.044Z [err] ERR! command
2020-07-17T19:45:39.044Z [err]  "/usr/bin/node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
2020-07-17T19:45:39.045Z [err] gyp ERR!
2020-07-17T19:45:39.045Z [err]  cwd /config/node-red/node_modules/@serialport/bindings
2020-07-17T19:45:39.045Z [err] gyp 
2020-07-17T19:45:39.045Z [err] ERR! 
2020-07-17T19:45:39.045Z [err] node -v v12.17.0
2020-07-17T19:45:39.045Z [err] gyp 
2020-07-17T19:45:39.045Z [err] ERR! 
2020-07-17T19:45:39.045Z [err] node-gyp -v v5.1.0
2020-07-17T19:45:39.046Z [err] gyp 
2020-07-17T19:45:39.046Z [err] ERR! 
2020-07-17T19:45:39.046Z [err] not ok 
2020-07-17T19:45:41.616Z [err] npm
2020-07-17T19:45:41.616Z [err]  ERR! code ELIFECYCLE
2020-07-17T19:45:41.616Z [err] npm 
2020-07-17T19:45:41.616Z [err] ERR! errno 1
2020-07-17T19:45:41.621Z [err] npm 
2020-07-17T19:45:41.621Z [err] ERR! @serialport/bindings@8.0.8 install: `prebuild-install --tag-prefix @serialport/bindings@ || node-gyp rebuild`
2020-07-17T19:45:41.621Z [err] npm ERR!
2020-07-17T19:45:41.621Z [err]  Exit status 1
2020-07-17T19:45:41.621Z [err] npm
2020-07-17T19:45:41.622Z [err]  ERR!
2020-07-17T19:45:41.622Z [err]  
2020-07-17T19:45:41.622Z [err] npm 
2020-07-17T19:45:41.622Z [err] ERR! Failed at the @serialport/bindings@8.0.8 install script.
2020-07-17T19:45:41.622Z [err] npm 
2020-07-17T19:45:41.622Z [err] ERR!
2020-07-17T19:45:41.622Z [err]  This is probably not a problem with npm. There is likely additional logging output above.
2020-07-17T19:45:41.759Z [err] 
2020-07-17T19:45:41.760Z [err] npm ERR!
2020-07-17T19:45:41.760Z [err]  A complete log of this run can be found in:
2020-07-17T19:45:41.760Z [err] npm 
2020-07-17T19:45:41.760Z [err] ERR!
2020-07-17T19:45:41.761Z [err]      /root/.npm/_logs/2020-07-17T19_45_41_705Z-debug.log
2020-07-17T19:45:41.795Z rc=1`

**Comment by coolchip** [comment]
#23 Please look at this issue
