### ISSUE TITLE
Unhandled promise rejection: addData (processData)

### ISSUE THREAD

**Issue by MichaelAnders** [coolchip/node-red-contrib-smartmeter#17]
I've been using the "OBIS" module in FHEM for many years and it works fine. I'm now migrating to Node-Red and this library has worked quite well for the first hours today.

But suddenly it no longer works as the code constantly crashes at the same spot and stops:

at SerialResponseTransport.processData (/home/bjoern/.node-red/node_modules/smartmeter-obis/lib/transports/SerialResponseTransport.js:149:37)
at SerialPort.<anonymous> (/home/bjoern/.node-red/node_modules/smartmeter-obis/lib/transports/SerialResponseTransport.js:83:25)
at SerialPort.emit (events.js:315:20)
at SerialPort.EventEmitter.emit (domain.js:483:12)
at addChunk (_stream_readable.js:295:12)
at readableAddChunk (_stream_readable.js:271:9)
at SerialPort.Readable.push (_stream_readable.js:212:10)
at /home/bjoern/.node-red/node_modules/@serialport/stream/lib/index.js:385:12
UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which w
[DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js

Temporary fix from my side:
        var addData;

try { addData = self.protocol.handleMessage(self.currentData.slice(0, self.currentDataOffset));
        } catch (e) {
}

Now at least I see "SCHEDULE NEXT RUN IN ..." - but no data is ever collected...

**Comment by coolchip** [comment]
I use the module smartmeter-obis in this node-red module. But this module is not developed by me. It is from https://github.com/Apollon77/smartmeter-obis. Please ask him or update node-red-contrib-smartmeter. I've added a new version of smartmeter-obis.
