### ISSUE TITLE
Could not install node-red-contrib-smartmeter with Node-RED v4.0.2 running in Home Assistant 

### ISSUE THREAD

**Issue by reindeer199** [coolchip/node-red-contrib-smartmeter#67]
2024-07-19T21:24:08.867Z Installieren : node-red-contrib-smartmeter 0.6.3

2024-07-19T21:24:08.949Z npm install --no-audit --no-update-notifier --no-fund --save --save-prefix=~ --omit=dev --engine-strict node-red-contrib-smartmeter@0.6.3
2024-07-19T21:24:24.781Z [err] npm warn deprecated har-validator@5.1.5: this library is no longer supported
2024-07-19T21:24:25.041Z [err] npm warn deprecated uuid@3.4.0: Please upgrade to version 7 or higher. Older versions may use Math.random() in certain circumstances, which is known to be problematic. See https://v8.dev/blog/math-random for details.
2024-07-19T21:24:25.314Z [err] npm warn deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
2024-07-19T21:24:26.875Z [err] npm error code 1
2024-07-19T21:24:26.875Z [err] npm error path /config/node_modules/@serialport/bindings
2024-07-19T21:24:26.881Z [err] npm error command failed
2024-07-19T21:24:26.881Z [err] npm error command sh -c prebuild-install --tag-prefix @serialport/bindings@ || node-gyp rebuild
2024-07-19T21:24:26.881Z [err] npm error prebuild-install warn install No prebuilt binaries found (target=18.20.3 runtime=node arch=arm64 libc=musl platform=linux)
2024-07-19T21:24:26.881Z [err] npm error gyp info it worked if it ends with ok
2024-07-19T21:24:26.881Z [err] npm error gyp info using node-gyp@10.1.0
2024-07-19T21:24:26.881Z [err] npm error gyp info using node@18.20.3 | linux | arm64
2024-07-19T21:24:26.881Z [err] npm error gyp ERR! find Python 
2024-07-19T21:24:26.881Z [err] npm error gyp ERR! find Python Python is not set from command line or npm configuration
2024-07-19T21:24:26.881Z [err] npm error gyp ERR! find Python Python is not set from environment variable PYTHON
2024-07-19T21:24:26.881Z [err] npm error gyp ERR! find Python checking if "python3" can be used
2024-07-19T21:24:26.881Z [err] npm error gyp ERR! find Python - executable path is ""
2024-07-19T21:24:26.881Z [err] npm error gyp ERR! find Python - "" could not be run
2024-07-19T21:24:26.881Z [err] npm error gyp ERR! find Python checking if "python" can be used
2024-07-19T21:24:26.881Z [err] npm error gyp ERR! find Python - executable path is ""
2024-07-19T21:24:26.881Z [err] npm error gyp ERR! find Python - "" could not be run
2024-07-19T21:24:26.881Z [err] npm error gyp ERR! find Python 
2024-07-19T21:24:26.881Z [err] npm error gyp ERR! find Python **********************************************************
2024-07-19T21:24:26.881Z [err] npm error gyp ERR! find Python You need to install the latest version of Python.
2024-07-19T21:24:26.881Z [err] npm error gyp ERR! find Python Node-gyp should be able to find and use Python. If not,
2024-07-19T21:24:26.881Z [err] npm error gyp ERR! find Python you can try one of the following options:
2024-07-19T21:24:26.881Z [err] npm error gyp ERR! find Python - Use the switch --python="/path/to/pythonexecutable"
2024-07-19T21:24:26.881Z [err] npm error gyp ERR! find Python (accepted by both node-gyp and npm)
2024-07-19T21:24:26.881Z [err] npm error gyp ERR! find Python - Set the environment variable PYTHON
2024-07-19T21:24:26.881Z [err] npm error gyp ERR! find Python - Set the npm configuration variable python:
2024-07-19T21:24:26.881Z [err] npm error gyp ERR! find Python npm config set python "/path/to/pythonexecutable"
2024-07-19T21:24:26.881Z [err] npm error gyp ERR! find Python For more information consult the documentation at:
2024-07-19T21:24:26.881Z [err] npm error gyp ERR! find Python https://github.com/nodejs/node-gyp#installation
2024-07-19T21:24:26.881Z [err] npm error gyp ERR! find Python **********************************************************
2024-07-19T21:24:26.881Z [err] npm error gyp ERR! find Python 
2024-07-19T21:24:26.881Z [err] npm error gyp ERR! configure error 
2024-07-19T21:24:26.881Z [err] npm error gyp ERR! stack Error: Could not find any Python installation to use
2024-07-19T21:24:26.881Z [err] npm error gyp ERR! stack at PythonFinder.fail (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/find-python.js:306:11)
2024-07-19T21:24:26.881Z [err] npm error gyp ERR! stack at PythonFinder.findPython (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/find-python.js:164:17)
2024-07-19T21:24:26.881Z [err] npm error gyp ERR! stack at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
2024-07-19T21:24:26.881Z [err] npm error gyp ERR! stack at async configure (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:27:18)
2024-07-19T21:24:26.881Z [err] npm error gyp ERR! stack at async run (/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js:81:18)
2024-07-19T21:24:26.881Z [err] npm error gyp ERR! System Linux 6.6.31-haos-raspi
2024-07-19T21:24:26.881Z [err] npm error gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
2024-07-19T21:24:26.881Z [err] npm error gyp ERR! cwd /config/node_modules/@serialport/bindings
2024-07-19T21:24:26.881Z [err] npm error gyp ERR! node -v v18.20.3
2024-07-19T21:24:26.881Z [err] npm error gyp ERR! node-gyp -v v10.1.0
2024-07-19T21:24:26.881Z [err] npm error gyp ERR! not ok
2024-07-19T21:24:26.886Z [err] 
2024-07-19T21:24:26.887Z [err] npm error A complete log of this run can be found in: /root/.npm/_logs/2024-07-19T21_24_09_277Z-debug-0.log
2024-07-19T21:24:26.913Z rc=1

**Comment by slev1n** [comment]
Hi @reindeer199, 
your have to add system packages to the bordered config in ha:

system_packages:
  - build-base
  - python3
  - linux-headers
  - eudev

Be aware that the latest version (19.0.0) will not work. See https://github.com/coolchip/node-red-contrib-smartmeter/issues/68
